### ISSUE TITLE
webREPL sends old file data: unexpected UI behaviour

### ISSUE THREAD

**Issue by peterhinch** [micropython/webrepl#8]
Usage: send a program to the esp8266, run it then modify the source. Use webREPL to re-send the updated source. The UI still shows the name of the file, and pressing 'Send to device' apparently works. However it behaves as if the old file were buffered re-sending the old data. It seems to be necessary to browse for the file again to force it to load the new version.

While not a major issue it is likely to confuse newcomers.

**Comment by dpgeorge** [comment]
This should be fixed by #14.

**Comment by osresearch** [comment]
OSX still has problems with this in Safari and Chrome - the old file contents are sent unless a different file is selected in the requestor and then the original file is reselected.  Firefox and Chrome on Linux do the right thing and will update the device with the new file length and contents.

**Comment by osresearch** [comment]
Correction: this works with a local checkout, but not with the hosted version at http://micropython.org/webrepl.  This appears to have the same problem as https://github.com/micropython/webrepl/issues/15#issuecomment-466670992 -- the hosted version hasn't been updated in a while.

**Comment by dpgeorge** [comment]
> the hosted version hasn't been updated in a while.

Thanks for the report, it's now updated to the latest version.

**Comment by bulletmark** [comment]
I've been experimenting with Micropython on an ESP32 using Linux and experience this webrepl bug with current version esp32-20210418-v1.15.bin. If I just press the "send to device" button then the send appears to work but the old file is sent. I have to open the file dialog and select the file (again) so that the new file contents are sent, which really hampers the debug loop cycle. Happens in Chrome, Firefox, and GNOME Web so it not browser dependent.
